# Generated by Django 2.2.6 on 2020-03-02 10:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0002_auto_20200226_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='adsboard',
            name='title',
            field=models.CharField(error_messages={'invalid': 'Wrong item name!'}, max_length=50, validators=[django.core.validators.RegexValidator(regex='^.{4,}$')], verbose_name='Name'),
        ),
        migrations.AddIndex(
            model_name='adsboard',
            index=models.Index(fields=['-published', 'title'], name='main'),
        ),
        migrations.AddIndex(
            model_name='adsboard',
            index=models.Index(fields=['title', 'price', 'rubric'], name='bboard_adsb_title_f8c6e1_idx'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spares',
            field=models.ManyToManyField(to='bboard.Spare'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
